// SYMBOL_TABLE
#define DECLARATION_PREDICATE 0
#define DECLARATION_FUNCTION 1
#define DECLARATION_VARIABLE 2

// SYNTAX_TREE
//0 children
#define NODE_TRUE 0
#define NODE_FALSE 1

//1 child
#define NODE_NEGATION 2
#define NODE_VARIABLE 3
#define NODE_NUMBER 4

//2 children
#define NODE_ALL 5
#define NODE_EXIST 6
#define NODE_CONJUNCTION 7
#define NODE_DISJUNCTION 8
#define NODE_IMPLICATION 9
#define NODE_EQUIVALENT 10
#define NODE_PREDICATE 11
#define NODE_FUNCTION 12
#define NODE_ARGUMENT 13