CC= gcc
LEX= flex
YACC= bison

all: parser scanner compile link

parser:
	$(YACC) -d parser/parser.y
	mv parser.tab.c parser/parser.tab.c
	mv parser.tab.h parser/parser.tab.h

scanner:
	$(lex) -t scanner/scanner.l > scanner/scanner.c

compile:
	@gcc -c -o bin/scanner.o scanner/scanner.c
	@gcc -c -o bin/parser.tab.o parser/parser.tab.c
	@gcc -c -o bin/symboltable.o symboltable/symboltable.c
	@gcc -c -o bin/syntaxtree.o syntaxtree/syntaxtree.c
	@echo "compilation successful"

link:
	@gcc bin/scanner.o bin/symboltable.o bin/syntaxtree.o bin/parser.tab.o -o pl
	@echo "linking successful.\nCall './pl input/filename.pl' to run the program"